services:
  postgres:
    image: postgres:17

    container_name: datasense_postgres

    environment:
      POSTGRES_USER: datasense_user
      POSTGRES_PASSWORD: datasense_password
      POSTGRES_DB: datasense_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: